name: Koboldcpp Builder Linux

on: workflow_dispatch
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: concedo_experimental

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install git curl bzip2

      - name: Build
        id: make_build
        run: |
          ./koboldcpp.sh dist

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: kcpp_linux_binary
          path: dist/
