name: Koboldcpp Builder Windows CUDA

on: workflow_dispatch
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  windows:
    runs-on: windows-2019
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: concedo_experimental

      - uses: Jimver/cuda-toolkit@v0.2.11
        id: cuda-toolkit
        with:
          cuda: '11.4.4'
        
      - name: Build
        id: cmake_build
        run: |
          mkdir build
          cd build
          cmake .. -DLLAMA_CUBLAS=ON -DCMAKE_SYSTEM_VERSION="10.0.19041.0"
          cmake --build . --config Release -j ${env:NUMBER_OF_PROCESSORS}

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: kcpp_windows_cuda_binary
          path: build/bin/Release/
